# Generated by Django 2.1.4 on 2018-12-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181221_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0),
        ),
    ]
